# Generated by Django 4.2.10 on 2025-01-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0071_laboratory_is_visible_iso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع صف')),
                ('end_time', models.TimeField(verbose_name='زمان پایان صف')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='زمان شروع استراحت')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='زمان پایان استراحت')),
                ('time_unit', models.IntegerField(verbose_name='مدت زمان نوبت (دقیقه)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10, verbose_name='وضعیت صف')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='lab.experiment', verbose_name='آزمون')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع نوبت')),
                ('status', models.CharField(choices=[('free', 'آزاد'), ('reserved', 'رزرو شده'), ('canceled', 'لغو شده')], default='free', max_length=50, verbose_name='وضعیت نوبت')),
                ('reserved_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='رزرو شده توسط')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.queue', verbose_name='صف')),
            ],
            options={
                'unique_together': {('queue', 'start_time')},
            },
        ),
    ]
