# Generated by Django 4.2.10 on 2025-03-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
