# Generated by Django 4.2.10 on 2025-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='زمان به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('free', 'آزاد'), ('reserved', 'رزرو شده'), ('pending', 'در انتظار پرداخت'), ('canceled', 'لغو شده')], default='free', max_length=50, verbose_name='وضعیت نوبت'),
        ),
    ]
