from django.urls import path

from apps.fundzi.api.views import (
    AdminPartnerDetailView,
    AdminPartnerListView,
    AdminRequestArchiveView,
    AdminRequestAssignView,
    AdminRequestAttachmentDetailView,
    AdminRequestAttachmentListView,
    AdminRequestDetailView,
    AdminRequestListView,
    AdminRequestNoteView,
    AdminRequestStatusView,
    AdminServiceContentDetailView,
    AdminServiceContentListView,
    AdminServiceDetailView,
    AdminServiceFieldDetailView,
    AdminServiceFieldListView,
    AdminServiceFormView,
    AdminServiceListView,
    AdminServiceWorkflowStepDetailView,
    AdminServiceWorkflowStepListView,
    AdminServiceWorkflowView,
    AdminStatsView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserSetRoleView,
    CurrentUserView,
    HealthCheckView,
    LogoutView,
    NotificationListView,
    NotificationReadAllView,
    NotificationReadView,
    NotificationUnreadCountView,
    PasswordLoginView,
    RequestDetailView,
    RequestHistoryView,
    RequestListView,
    SendOtpView,
    ServiceRequestCreateView,
    VerifyOtpView,
    service_detail_view,
    service_form_view,
    service_list,
)


urlpatterns = [
    path('auth/send-otp/', SendOtpView.as_view(), name='fundzi-auth-send-otp'),
    path('auth/verify-otp/', VerifyOtpView.as_view(), name='fundzi-auth-verify-otp'),
    path('auth/login/', PasswordLoginView.as_view(), name='fundzi-auth-login'),
    path('auth/me/', CurrentUserView.as_view(), name='fundzi-auth-me'),
    path('auth/logout/', LogoutView.as_view(), name='fundzi-auth-logout'),
    path('services/', service_list, name='fundzi-service-list'),
    path('services/<slug:slug>/', service_detail_view, name='fundzi-service-detail'),
    path('services/<slug:slug>/form/', service_form_view, name='fundzi-service-form'),
    path('services/<slug:slug>/requests/', ServiceRequestCreateView.as_view(), name='fundzi-service-request-create'),
    path('requests/', RequestListView.as_view(), name='fundzi-request-list'),
    path('requests/<int:pk>/', RequestDetailView.as_view(), name='fundzi-request-detail'),
    path('requests/<int:pk>/history/', RequestHistoryView.as_view(), name='fundzi-request-history'),
    path('notifications/', NotificationListView.as_view(), name='fundzi-notification-list'),
    path('notifications/unread-count/', NotificationUnreadCountView.as_view(), name='fundzi-notification-unread-count'),
    path('notifications/read-all/', NotificationReadAllView.as_view(), name='fundzi-notification-read-all'),
    path('notifications/<int:pk>/read/', NotificationReadView.as_view(), name='fundzi-notification-read'),
    path('admin/requests/', AdminRequestListView.as_view(), name='fundzi-admin-request-list'),
    path('admin/stats/', AdminStatsView.as_view(), name='fundzi-admin-stats'),
    path('admin/requests/<int:pk>/', AdminRequestDetailView.as_view(), name='fundzi-admin-request-detail'),
    path('admin/requests/<int:pk>/status/', AdminRequestStatusView.as_view(), name='fundzi-admin-request-status'),
    path('admin/requests/<int:pk>/notes/', AdminRequestNoteView.as_view(), name='fundzi-admin-request-note'),
    path('admin/requests/<int:pk>/assign/', AdminRequestAssignView.as_view(), name='fundzi-admin-request-assign'),
    path('admin/requests/<int:pk>/archive/', AdminRequestArchiveView.as_view(), name='fundzi-admin-request-archive'),
    path('admin/requests/<int:pk>/attachments/', AdminRequestAttachmentListView.as_view(), name='fundzi-admin-request-attachment-list'),
    path('admin/requests/<int:pk>/attachments/<int:att_id>/', AdminRequestAttachmentDetailView.as_view(), name='fundzi-admin-request-attachment-detail'),
    path('admin/services/', AdminServiceListView.as_view(), name='fundzi-admin-service-list'),
    path('admin/services/<int:pk>/', AdminServiceDetailView.as_view(), name='fundzi-admin-service-detail'),
    path('admin/services/<int:service_id>/contents/', AdminServiceContentListView.as_view(), name='fundzi-admin-service-content-list'),
    path('admin/services/<int:service_id>/contents/<int:content_id>/', AdminServiceContentDetailView.as_view(), name='fundzi-admin-service-content-detail'),
    path('admin/services/<int:service_id>/form/', AdminServiceFormView.as_view(), name='fundzi-admin-service-form'),
    path('admin/services/<int:service_id>/form/fields/', AdminServiceFieldListView.as_view(), name='fundzi-admin-service-field-list'),
    path('admin/services/<int:service_id>/form/fields/<int:field_id>/', AdminServiceFieldDetailView.as_view(), name='fundzi-admin-service-field-detail'),
    path('admin/services/<int:service_id>/workflow/', AdminServiceWorkflowView.as_view(), name='fundzi-admin-service-workflow'),
    path('admin/services/<int:service_id>/workflow/steps/', AdminServiceWorkflowStepListView.as_view(), name='fundzi-admin-service-workflow-step-list'),
    path('admin/services/<int:service_id>/workflow/steps/<int:step_id>/', AdminServiceWorkflowStepDetailView.as_view(), name='fundzi-admin-service-workflow-step-detail'),
    path('admin/users/', AdminUserListView.as_view(), name='fundzi-admin-user-list'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='fundzi-admin-user-detail'),
    path('admin/users/<int:pk>/set-role/', AdminUserSetRoleView.as_view(), name='fundzi-admin-user-set-role'),
    path('admin/partners/', AdminPartnerListView.as_view(), name='fundzi-admin-partner-list'),
    path('admin/partners/<int:pk>/', AdminPartnerDetailView.as_view(), name='fundzi-admin-partner-detail'),
    path('health/', HealthCheckView.as_view(), name='fundzi-health'),
]
