# Generated by Django 4.2.10 on 2024-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
