# Generated by Django 4.2.10 on 2024-03-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='json',
        ),
    ]
