# Generated by Django 4.2.10 on 2024-04-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0021_alter_workflowstep_next_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('user', 'کاربر'), ('expert', 'کارشناس')], default='user', help_text="Choices: ['user', 'expert']", max_length=31, verbose_name='نوع سفارش')),
                ('order_status', models.CharField(choices=[('new', 'جدید'), ('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('canceled', 'لغو شده')], default='new', help_text="Choices: ['new', 'pending', 'completed', 'canceled']", max_length=31, verbose_name='وضعیت سفارش')),
                ('amount_wo_pc', models.PositiveIntegerField(default=0, verbose_name='مقدار بدون تخفیف')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('paid', models.PositiveIntegerField(default=0, verbose_name='میزان پرداختی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='کد سفارش')),
                ('order_key', models.CharField(blank=True, max_length=31, null=True, unique=True, verbose_name='کلید سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_orders', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('percent_off', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('usable_count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مقدار')),
                ('returned', models.BooleanField(default=False, help_text='Shows if the money is returned to user profile. (When order is canceled)', verbose_name='بازگشت اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='order.order', verbose_name='سفارش')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Transaction Record',
                'verbose_name_plural': 'Transaction Records',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='order.order', verbose_name='سفارش')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'بلیت',
                'verbose_name_plural': 'بلیت ها',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('order', 'پرداخت سفارش'), ('account', 'شارژ اکانت')], default='order', help_text="Choices: ['شارژ اکانت', 'پرداخت سفارش']", max_length=31, verbose_name='نوع پرداخت')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مقدار')),
                ('successful', models.BooleanField(default=False, verbose_name='موفق')),
                ('charged', models.BooleanField(default=False, verbose_name='شارژ شده')),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد تراکنش')),
                ('tref', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد مرجع بانک')),
                ('payment_order_guid', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد درگاه')),
                ('payment_order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد سفارش درگاه')),
                ('payment_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک درگاه')),
                ('called_back', models.BooleanField(default=False, verbose_name='برگشت')),
                ('log_text', models.TextField(default='', verbose_name='Log Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(blank=True, help_text='The order we want to pay for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='order.order', verbose_name='سفارش')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش های پرداخت',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.promotioncode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.request', verbose_name='رویداد'),
        ),
    ]
