# Generated by Django 4.2.10 on 2024-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='عودت شده'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='عودت شده'),
        ),
    ]
