# Generated by Django 4.2.10 on 2024-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_returned_paymentrecord_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='مبلغ عودت شده'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='مبلغ عودت شده'),
        ),
    ]
