# Generated by Django 4.2.10 on 2024-09-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='settlement_type',
            field=models.CharField(choices=[('order', 'پرداخت سفارش'), ('account', 'شارژ اکانت')], default='opay', help_text="Choices: ['درگاه', 'کارتخوان']", max_length=31, verbose_name='نوع تسویه'),
        ),
    ]
