# Generated by Django 4.2.10 on 2024-09-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_paymentrecord_settlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='settlement_type',
            field=models.CharField(choices=[('pos', 'کارتخوان'), ('opay', 'درگاه')], default='opay', help_text="Choices: ['درگاه', 'کارتخوان']", max_length=31, verbose_name='نوع تسویه'),
        ),
    ]
