# Generated by Django 4.2.10 on 2024-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_paymentrecord_settlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='log_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Log Text'),
        ),
    ]
