# Generated by Django 4.2.10 on 2024-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_paymentrecord_log_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='قفل شده'),
        ),
    ]
