# Generated by Django 4.2.10 on 2024-10-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_grantrequest_remaining_amount'),
        ('order', '0008_paymentrecord_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grant_request1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gr_order1', to='account.grantrequest'),
        ),
        migrations.AddField(
            model_name='order',
            name='grant_request2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gr_order2', to='account.grantrequest'),
        ),
    ]
