# Generated by Django 4.2.10 on 2024-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_paymentrecord_settlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='settlement_type',
            field=models.CharField(choices=[('pos', 'کارتخوان'), ('iopay', 'درگاه داخلی'), ('eopay', 'درگاه خارجی'), ('cash', 'نقدی')], default='iopay', help_text="Choices: ['درگاه', 'کارتخوان']", max_length=31, verbose_name='نوع تسویه'),
        ),
    ]
