# Generated by Django 4.2.10 on 2025-04-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_paymentrecord_settlement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.CharField(choices=[('order', 'پرداخت سفارش'), ('account', 'شارژ اکانت'), ('prepayment', 'پیش پرداخت')], default='order', help_text="Choices: ['شارژ اکانت', 'پرداخت سفارش', 'پیش پرداخت']", max_length=31, verbose_name='نوع پرداخت'),
        ),
    ]
