# Generated by Django 4.2.10 on 2025-05-26 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_alter_paymentrecord_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order we want to pay for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_payment_records', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_payment_records', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
    ]
