# Generated by Django 4.2.10 on 2025-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_paymentrecord_order_alter_paymentrecord_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_prepayment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ نهایی پیش\u200cپرداخت پس از تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='grant_discount_prepayment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کسر شده از گرنت'),
        ),
        migrations.AddField(
            model_name='order',
            name='labsnet_discount_prepayment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کسر شده از لبزنت'),
        ),
    ]
