# Generated by Django 4.2.10 on 2025-08-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_final_prepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid at'),
        ),
    ]
