# Generated by Django 4.2.10 on 2025-08-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_paymentrecord_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='settlement_type',
            field=models.CharField(choices=[('pos', 'کارتخوان'), ('iopay', 'درگاه پرداخت شریف'), ('bank', 'پرداخت بانکی'), ('eopay', 'درگاه خارجی'), ('cash', 'نقدی')], default='iopay', help_text="Choices: ['درگاه', 'کارتخوان']", max_length=31, verbose_name='نوع تسویه'),
        ),
    ]
