# Generated by Django 5.2.11 on 2026-06-22 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=120)),
                ('service_categories', models.JSONField(blank=True, default=list)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('accepted_collateral_types', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'همکار مالی',
                'verbose_name_plural': 'همکاران مالی',
            },
        ),
        migrations.CreateModel(
            name='FinancialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('full_description', models.TextField(blank=True, verbose_name='توضیح کامل')),
                ('service_type', models.CharField(choices=[('gold_backed', 'Gold-backed financing'), ('property_backed', 'Property-backed financing'), ('other', 'Other')], default='other', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('rules_config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات و قواعد')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سرویس مالی',
                'verbose_name_plural': 'سرویس\u200cهای مالی',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='fundzi.financialservice')),
            ],
            options={
                'verbose_name': 'فرم پویا',
                'verbose_name_plural': 'فرم\u200cهای پویا',
            },
        ),
        migrations.CreateModel(
            name='FinancingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('admin_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fundzi_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='fundzi.financialservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundzi_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درخواست تأمین مالی',
                'verbose_name_plural': 'درخواست\u200cهای تأمین مالی',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Select'), ('multi_select', 'Multi select'), ('boolean', 'Boolean'), ('date', 'Date'), ('file', 'File'), ('money', 'Money'), ('percentage', 'Percentage')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='fundzi.dynamicform')),
            ],
            options={
                'verbose_name': 'فیلد فرم',
                'verbose_name_plural': 'فیلدهای فرم',
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'key')},
            },
        ),
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='fundzi.financingrequest')),
            ],
            options={
                'verbose_name': 'یادداشت داخلی',
                'verbose_name_plural': 'یادداشت\u200cهای داخلی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fundzi/attachments/')),
                ('document_type', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fundzi.financingrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیوست درخواست',
                'verbose_name_plural': 'پیوست\u200cهای درخواست',
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=120, null=True)),
                ('to_status', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fundzi.financingrequest')),
            ],
            options={
                'verbose_name': 'تاریخچه درخواست',
                'verbose_name_plural': 'تاریخچه درخواست\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('introduction', 'Introduction'), ('conditions', 'Conditions'), ('required_documents', 'Required documents'), ('process_steps', 'Process steps'), ('faq', 'FAQ'), ('warning', 'Warning'), ('help_text', 'Help text')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='fundzi.financialservice')),
            ],
            options={
                'verbose_name': 'محتوای سرویس',
                'verbose_name_plural': 'محتوای سرویس\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='fundzi.financialservice')),
            ],
            options={
                'verbose_name': 'گردش کار فندزی',
                'verbose_name_plural': 'گردش کارهای فندزی',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='fundzi.workflow')),
            ],
            options={
                'verbose_name': 'مرحله گردش کار فندزی',
                'verbose_name_plural': 'مراحل گردش کار فندزی',
                'ordering': ['order', 'id'],
                'unique_together': {('workflow', 'key')},
            },
        ),
        migrations.AddField(
            model_name='financingrequest',
            name='current_workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_requests', to='fundzi.workflowstep'),
        ),
        migrations.CreateModel(
            name='RequestFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='fundzi/field-values/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='fundzi.formfield')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='fundzi.financingrequest')),
            ],
            options={
                'verbose_name': 'مقدار فیلد درخواست',
                'verbose_name_plural': 'مقادیر فیلدهای درخواست',
                'unique_together': {('request', 'field')},
            },
        ),
    ]
