# Generated by Django 5.2.11 on 2026-06-29 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundzi', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='fundzi.financialpartner')),
            ],
            options={
                'verbose_name': 'قانون تطبیق',
                'verbose_name_plural': 'قوانین تطبیق',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.PositiveIntegerField()),
                ('conditions', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='fundzi.financialpartner')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_offers', to='fundzi.financingrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد همکار',
                'verbose_name_plural': 'پیشنهادهای همکار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('assigned', 'Assigned'), ('rejected', 'Rejected')], default='matched', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='fundzi.financialpartner')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='fundzi.financingrequest')),
            ],
            options={
                'verbose_name': 'نتیجه تطبیق',
                'verbose_name_plural': 'نتایج تطبیق',
                'ordering': ['-score'],
                'unique_together': {('request', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='PartnerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst')], default='analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fundzi.financialpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر همکار',
                'verbose_name_plural': 'کاربران همکار',
                'unique_together': {('user', 'partner')},
            },
        ),
    ]
