# Generated by Django 5.2.11 on 2026-06-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundzi', '0003_phase3_partner_matching'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('vendor_type', models.CharField(choices=[('financial', 'مالی'), ('non_financial', 'غیرمالی')], max_length=30, verbose_name='نوع')),
                ('logo_url', models.URLField(blank=True, verbose_name='لوگو')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وندور',
                'verbose_name_plural': 'وندورها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='financialservice',
            name='dashboard_section',
            field=models.CharField(choices=[('investment', 'سرمایه\u200cگذاری'), ('financing', 'تامین مالی')], default='financing', max_length=30, verbose_name='بخش داشبورد'),
        ),
        migrations.AlterField(
            model_name='financialservice',
            name='service_type',
            field=models.CharField(choices=[('gold_backed', 'Gold-backed financing'), ('property_backed', 'Property-backed financing'), ('crowdfunding', 'Crowdfunding'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('crowdfunding', 'تامین مالی جمعی'), ('business_consulting', 'مشاوره کسب\u200cوکار'), ('legal', 'خدمات حقوقی'), ('credit_scoring', 'اعتبارسنجی و رتبه\u200cبندی'), ('accounting', 'حسابداری و مالی'), ('valuation', 'ارزیابی دارایی'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('price_display', models.CharField(blank=True, max_length=100, verbose_name='نمایش قیمت')),
                ('duration_display', models.CharField(blank=True, max_length=100, verbose_name='زمان تحویل')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fundzi.vendor')),
            ],
            options={
                'verbose_name': 'سرویس وندور',
                'verbose_name_plural': 'سرویس\u200cهای وندور',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('under_review', 'در حال بررسی'), ('awaiting_info', 'نیاز به اطلاعات بیشتر'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=30)),
                ('user_notes', models.TextField(blank=True, verbose_name='توضیحات متقاضی')),
                ('vendor_notes', models.TextField(blank=True, verbose_name='یادداشت وندور')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='خروجی')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financing_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_applications', to='fundzi.financingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL)),
                ('vendor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fundzi.vendorservice')),
            ],
            options={
                'verbose_name': 'درخواست وندور',
                'verbose_name_plural': 'درخواست\u200cهای وندور',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
