# Generated by Django 5.2.11 on 2026-07-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundzi', '0004_phase4_vendor_ecosystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='group_option',
            field=models.CharField(blank=True, max_length=255, verbose_name='گزینه فعال\u200cکننده گروه'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fundzi.formfield', verbose_name='فیلد والد (گروه)'),
        ),
    ]
